logging.level:
  com.falabella.rplm: DEBUG
spring:
  application:
    name: digital-product

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

digital-product:
  config:
      product-external-info-endpoint: ${PRODUCT_EXT_INFO_ENDPOINT}