logging:
  level:
    com.demo.digitalproduct: INFO
  file.name: logs/application-info.log

spring:
  application:
    name: digital-product
  jpa:
    show-sql: ${SHOW_SQL:false}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jmx:
    enabled: false
flyway:
  enabled: true
  schemas: ${FLYWAY_SCHEMA}
  url: ${FLYWAY_URL}
  user: ${FLYWAY_USER}
  password: ${FLYWAY_PASSWORD}

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include:
          - health

digital-product:
  config:
      product-external-info-endpoint: ${PRODUCT_EXT_INFO_ENDPOINT}